[build]
  base = "/"  # The directory where the build command runs from (optional)
  command = ""  # Leave empty if you don't need a build command
  publish = "/"  # Directory to publish; should be the root if no build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
